#!/bin/bash
curl -O -fsSL https://golang.org/dl/go1.19.linux-amd64.tar.gz
tar xvf go1.19.linux-amd64.tar.gz
mv go ~/.go
rm -rf go go1.19.linux-amd64.tar.gz
sudo chown -R root:root ~/.go
echo '#go' >> ~/.zshrc
echo 'export PATH=$PATH:$HOME/.go/bin' >> ~/.zshrc
# source later 
#. ~/.zshrc
