#!/bin/bash

curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.0/install.sh | zsh
nvm install --lts
echo 'export LC_ALL=C.UTF-8' >> ~/.zshrc
source ~/.zshrc

#### optional 
# if u have that manpath error run:
# sudo locale-gen en_US.UTF-8
# sudo update-locale LANG=en_US.UTF-8