#!/bin/bash

curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.0/install.sh | sh
nvm install --lts

cat >>  ~./zshrc <<'EOF'
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  
export LC_ALL=C.UTF-8' 
EOF

source ~/.zshrc

#### optional 
# if u have that manpath error run:
# sudo locale-gen en_US.UTF-8
# sudo update-locale LANG=en_US.UTF-8
