#!/bin/bash

wget -qO- https://get.pnpm.io/install.sh | sh -

cat >>   ~/.zshrc <<'EOF'
# pnpm
export PNPM_HOME="$HOME/.local/share/pnpm"
case ":$PATH:" in
  *":$PNPM_HOME:"*) ;;
  *) export PATH="$PNPM_HOME:$PATH" ;;
esac
EOF

source  ~/.zshrc
