#!/bin/bash


# some distros be acting up
source_or_dot() {
  if command -v source &> /dev/null; then
    source "$1"
  else
    . "$1"
  fi
}

# nix setup
if ! command -v xz &> /dev/null; then
  if [ -f "/etc/debian_version" ]; then
    echo "xz not found. Installing xz-utils on Debian..."
    sudo apt update
    sudo apt -y install xz-utils
    echo "Also installing build essentials..:"
    sudo apt  -y install build-essential
  else
    echo "xz not found, and you are not on Debian, install it with your package manager to continue. Exiting."
    exit 1
  fi
fi

echo -e "\e[1;32mInstalling nix..\e[0m"

sh <(curl -L https://nixos.org/nix/install) --no-daemon
source_or_dot ~/.nix-profile/etc/profile.d/nix.sh

echo -e "\e[1;32mInstalling all the necessary packages..\e[0m"

# chad packages installation
nix-env -iA nixpkgs.git \
    nixpkgs.curl \
    nixpkgs.wget \
    nixpkgs.zsh \
    nixpkgs.neovim \
    nixpkgs.tmux \
    nixpkgs.bat \
    nixpkgs.python3 \
    nixpkgs.openssh \
    nixpkgs.neofetch \
    nixpkgs.tree \
    nixpkgs.htop \
    nixpkgs.fd \
    nixpkgs.xclip \
    nixpkgs.polybar \
    nixpkgs.feh \
    nixpkgs.man \
    nixpkgs.i3 \
    nixpkgs.picom \
    nixpkgs.pango \
    nixpkgs.ripgrep \
    nixpkgs.direnv \
    nixpkgs.librewolf \
    nixpkgs.chromium \
    nixpkgs.docker \
    nixpkgs.docker-compose \
    nixpkgs.kubectl \
    nixpkgs.virtualbox \
    nixpkgs.wireshark \
    nixpkgs.nmap \
    nixpkgs.pandoc \
    nixpkgs.zathura \
    nixpkgs.tor \
    nixpkgs.tor-browser

echo -e "\e[1;32mThe whole 9 setup..\e[0m"
#
mkdir work trash personal 
# tmux plugin manager
git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm


# dircolors
curl https://raw.githubusercontent.com/seebi/dircolors-solarized/master/dircolors.ansi-dark --output ~/.dircolors


# zsh setup

sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)" <<< $'\n'
rm -rf ~/.zshrc

mkdir ~/.config ~/.ssh ~/.config/nvim ~/.config/zathura ~/.config/neofetch ~/.config/picom ~/.config/polybar ~/.config/i3 

# dotfiles mapping

echo -e "\e[1;32mCopying the files into $HOME..\e[0m"

declare -A dotfiles=(
  [".zshrc"]="https://raw.githubusercontent.com/AshGw/dotfiles/main/.zshrc"
  [".dircolors"]="https://raw.githubusercontent.com/AshGw/dotfiles/main/.dircolors"
  [".bashrc"]="https://raw.githubusercontent.com/AshGw/dotfiles/main/.bashrc"
  [".nanorc"]="https://raw.githubusercontent.com/AshGw/dotfiles/main/.nanorc"
  [".tmux.conf"]="https://raw.githubusercontent.com/AshGw/dotfiles/main/.tmux.conf"
  [".gitconfig"]="https://raw.githubusercontent.com/AshGw/dotfiles/main/.gitconfig"
  [".hushlogin"]="https://raw.githubusercontent.com/AshGw/dotfiles/main/.hushlogin"
  [".config/nvim/init.vim"]="https://raw.githubusercontent.com/AshGw/dotfiles/main/.config/nvim/init.vim"
  [".config/zathura/zathurarc"]="https://raw.githubusercontent.com/AshGw/dotfiles/main/.config/zathura/zathurarc"
  [".config/i3/config"]="https://raw.githubusercontent.com/AshGw/dotfiles/main/.config/i3/config"
  [".config/polybar/colors.ini"]="https://raw.githubusercontent.com/AshGw/dotfiles/main/.config/polybar/colors.ini"
  [".config/polybar/config.ini"]="https://raw.githubusercontent.com/AshGw/dotfiles/main/.config/polybar/config.ini"
  [".config/polybar/launch.sh"]="https://raw.githubusercontent.com/AshGw/dotfiles/main/.config/polybar/launch.sh"
  [".config/polybar/uptime.sh"]="https://raw.githubusercontent.com/AshGw/dotfiles/main/.config/polybar/uptime.sh"
  [".config/neofetch/config.conf"]="https://raw.githubusercontent.com/AshGw/dotfiles/main/.config/neofetch/config.conf"
  [".config/picom/picom.conf"]="https://raw.githubusercontent.com/AshGw/dotfiles/main/.config/picom/picom.conf"
  [".ssh/_gh_gen.sh"]="https://raw.githubusercontent.com/AshGw/dotfiles/main/.ssh/_gh_gen.sh"
  [".ssh/config"]="https://raw.githubusercontent.com/AshGw/dotfiles/main/.ssh/config"

)

for file in "${!dotfiles[@]}"; do
  curl -o "$HOME/$file" "${dotfiles[$file]}"
done

#### zsh final confs
echo '#Nix' >> ~/.zshrc
echo '. ~/.nix-profile/etc/profile.d/nix.sh' >> ~/.zshrc
      ### zsh plugins ###
git clone https://github.com/zsh-users/zsh-autosuggestions.git $HOME/.oh-my-zsh/custom/plugins/zsh-autosuggestions
git clone https://github.com/zsh-users/zsh-syntax-highlighting.git $HOME/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting

##############################################
#### now for the extra shit 

read -p "Do you want to install all the arbitrary dev packages? (y/n): " ans

if [ "$ans" == "y" ]; then
    
    echo -e "\e[1;32mInstalling conda...\e[0m"
    bash <(curl -L https://raw.githubusercontent.com/AshGw/dotfiles/main/install/arbitrary/conda)
    echo -e "\e[1;32mconda installation done!\e[0m"

    echo -e "\e[1;32mInstalling node...\e[0m"
    bash <(curl -L https://raw.githubusercontent.com/AshGw/dotfiles/main/install/arbitrary/node)
    echo -e "\e[1;32mnode installation done!\e[0m"

    echo -e "\e[1;32mInstalling pnpm...\e[0m"
    bash <(curl -L https://raw.githubusercontent.com/AshGw/dotfiles/main/install/arbitrary/pnpm)
    echo -e "\e[1;32mpnpm installation done!\e[0m"

    echo -e "\e[1;32mInstalling poetry...\e[0m"
    bash <(curl -L https://raw.githubusercontent.com/AshGw/dotfiles/main/install/arbitrary/poetry)
    echo -e "\e[1;32mpoetry installation done!\e[0m"

    echo -e "\e[1;32mInstalling go...\e[0m"
    bash <(curl -L https://raw.githubusercontent.com/AshGw/dotfiles/main/install/arbitrary/go)
    echo -e "\e[1;32mgo installation done!\e[0m"

    echo -e "\e[1;32mInstalling rust...\e[0m"
    bash <(curl -L https://raw.githubusercontent.com/AshGw/dotfiles/main/install/arbitrary/rust)
    echo -e "\e[1;32mrust installation done!\e[0m"

    echo -e "\e[1;32mInstallation of arbitrary dev packages completed.\e[0m"
else
    echo "Skipping installation of arbitrary dev packages."
fi

#############

read -p $"Do you by any chance want to install some proprietary software? (y/n)\nThe list currently contains: Obsidian: " ans

if [ "$ans" == "y" ]; then
    echo -e "\e[1;32mInstalling Obsidian...\e[0m"
    bash <(curl -L https://raw.githubusercontent.com/AshGw/dotfiles/main/install/proprietary/obsidian)
    echo -e "\e[1;32mObsidian installation is complete!\e[0m"
else
    echo "Skipping the proprietary software installation."
fi


echo "Want to to set up GitHub SSH keys now?"
echo "(U will only need them to authenticate for the `post-bootstrap` step)"
read -p $"What u say ?(y/n): " ans

if [ "$ans" == "y" ]; then
    bash <(curl -L https://raw.githubusercontent.com/AshGw/dotfiles/main/.ssh/_gh_gen.sh)
    echo -e "\e[1;32mDone! The public key has been copied to your clipboard. Go paste it now on GitHub.\e[0m"
  

else
    echo "Aight, maybe later. You can run `ghkey` whenever youre ready to set it up."
fi


echo -e "\e[1;32mBootstrapping is complete!\e[0m"
echo -e "\e[1;36mYou might restart your shell for changes to take place\e[0m"








