#!/bin/bash

# nix setup
sh <(curl -L https://nixos.org/nix/install) --no-daemon

# ncessary packages installation
nix-env -iA \
    nixpkgs.git \
    nixpkgs.curl \
    nixpkgs.wget \
    nixpkgs.neovim \
    nixpkgs.neovim \

# zsh setup
command -v sh | sudo tee -a /etc/shells
sudo chsh -s $(which zsh) $USER
