#!/bin/bash

# nix setup

# if ure on bare metal debians hit <sudo apt update && sudo apt -y install xz-utils> for xz.
sh <(curl -L https://nixos.org/nix/install) --no-daemon
. /home/$USER/.nix-profile/etc/profile.d/nix.sh

# ncessary packages installation
nix-env -iA \
    nixpkgs.git \
    nixpkgs.curl \
    nixpkgs.wget \
    nixpkgs.zsh \
    nixpkgs.neovim \
    

# dircolors 
curl https://raw.githubusercontent.com/seebi/dircolors-solarized/master/dircolors.ansi-dark --output ~/.dircolors


# zsh setup
sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)" -y
sudo chsh -s $(which zsh) $USER
rm -rf .zshrc 
sh -c "$(curl -fsLS chezmoi.io/get)" -- init --apply  --verbose ashgw
. ~./zshrc
