name: Submodule Sync
on:
  schedule:
    - cron: "15 4 * * *" # Runs every day at 04:15 UTC
  workflow_dispatch:

jobs:
  submodule-sync:
    name: Submodule update
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          submodules: recursive
          token: ${{ secrets.PERSONAL_TOKEN }}

      - name: Pull latest commits for all submodules
        run: |
          git submodule foreach --recursive '
            echo "Updating $name..."
            git checkout main || git checkout master || exit 1
            git pull origin HEAD
          '

      - name: Commit updated submodule references
        run: |
          git add .
          git commit -m "auto updated submodule references" || echo "No changes to commit"
          git push || echo "No push needed"
