name: Sync Submodules Daily

on:
  schedule:
    - cron: '0 15 * * *'
  workflow_dispatch:

jobs:
  submodule-sync:
    name: Submodule update
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo with submodules using PAT
        uses: actions/checkout@v4
        with:
          submodules: recursive
          token: ${{ secrets.PERSONAL_TOKEN }}

      - name: Pull latest commits for all submodules
        run: |
          git submodule foreach --recursive '
            echo "Updating $name..."
            git checkout main || git checkout master || exit 1
            git pull origin HEAD
          '

      - name: Configure Git author
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Commit & push updates
        run: |
          git add .
          git commit -m "auto updated submodule references" || echo "No changes"
          git push || echo "No push needed"
